[build]
  command = "cd ai-concierge && npm install && npm run build-with-knowledge"
  publish = "ai-concierge/.next"

[build.environment]
  NODE_VERSION = "18"
  DEFAULT_LLM_PROVIDER = "claude"

# Functions configuration for better performance
[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Note: Environment variables should be set in Netlify UI:
# ANTHROPIC_API_KEY, GOOGLE_API_KEY, OPENAI_API_KEY