[build]
  base = "ai-concierge"
  command = "npm ci && npm run build-with-knowledge"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  DEFAULT_LLM_PROVIDER = "claude"

# Functions configuration for better performance
[functions]
  directory = "ai-concierge/.netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Note: Environment variables should be set in Netlify UI:
# ANTHROPIC_API_KEY, GOOGLE_API_KEY, OPENAI_API_KEY