# Staging environment patches for PRSM deployments
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: "512Mi"
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: "2Gi"
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: "250m"
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: "1000m"
- op: replace
  path: /spec/template/spec/containers/0/env/0/value
  value: "staging"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: LOG_LEVEL
    value: "INFO"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DEBUG_MODE
    value: "false"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: MONITORING_ENABLED
    value: "true"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: TRACING_SAMPLE_RATE
    value: "0.1"