groups:
# =============================================================================
# PRSM System Health Alerts
# =============================================================================
- name: prsm.system.health
  rules:
  - alert: PRSMServiceDown
    expr: up{job=~"prsm-.*"} == 0
    for: 30s
    labels:
      severity: critical
      service: "{{ $labels.job }}"
      category: availability
    annotations:
      summary: "PRSM service {{ $labels.job }} is down"
      description: "PRSM service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 30 seconds."
      runbook_url: "https://docs.prsm.org/runbooks/service-down"

  - alert: PRSMHighRestartRate
    expr: increase(kube_pod_container_status_restarts_total{container=~"prsm-.*"}[1h]) > 3
    for: 5m
    labels:
      severity: warning
      service: "{{ $labels.container }}"
      category: stability
    annotations:
      summary: "High restart rate for PRSM service {{ $labels.container }}"
      description: "PRSM service {{ $labels.container }} has restarted {{ $value }} times in the last hour."
      runbook_url: "https://docs.prsm.org/runbooks/high-restart-rate"

  - alert: PRSMPodCrashLooping
    expr: rate(kube_pod_container_status_restarts_total{container=~"prsm-.*"}[15m]) > 0
    for: 5m
    labels:
      severity: critical
      service: "{{ $labels.container }}"
      category: stability
    annotations:
      summary: "PRSM pod {{ $labels.pod }} is crash looping"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping with restart rate {{ $value }}/min."
      runbook_url: "https://docs.prsm.org/runbooks/crash-loop"

# =============================================================================
# PRSM API Performance Alerts
# =============================================================================
- name: prsm.api.performance
  rules:
  - alert: PRSMHighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="prsm-api"}[5m])) > 2
    for: 10m
    labels:
      severity: warning
      service: api
      category: performance
    annotations:
      summary: "High API response time detected"
      description: "PRSM API 95th percentile response time is {{ $value }}s, exceeding 2s threshold."
      runbook_url: "https://docs.prsm.org/runbooks/high-response-time"

  - alert: PRSMHighErrorRate
    expr: rate(http_requests_total{job="prsm-api", status=~"5.."}[5m]) / rate(http_requests_total{job="prsm-api"}[5m]) > 0.05
    for: 5m
    labels:
      severity: critical
      service: api
      category: reliability
    annotations:
      summary: "High API error rate detected"
      description: "PRSM API error rate is {{ $value | humanizePercentage }}, exceeding 5% threshold."
      runbook_url: "https://docs.prsm.org/runbooks/high-error-rate"

  - alert: PRSMAPIRateLimitReached
    expr: rate(http_requests_total{job="prsm-api", status="429"}[5m]) > 10
    for: 2m
    labels:
      severity: warning
      service: api
      category: capacity
    annotations:
      summary: "API rate limiting frequently triggered"
      description: "PRSM API is rate limiting {{ $value }} requests/second, indicating high load or potential abuse."
      runbook_url: "https://docs.prsm.org/runbooks/rate-limiting"

  - alert: PRSMLowThroughput
    expr: rate(http_requests_total{job="prsm-api"}[5m]) < 1
    for: 15m
    labels:
      severity: warning
      service: api
      category: performance
    annotations:
      summary: "Low API throughput detected"
      description: "PRSM API throughput is {{ $value }} requests/second, which is unusually low."
      runbook_url: "https://docs.prsm.org/runbooks/low-throughput"

# =============================================================================
# Database Health Alerts
# =============================================================================
- name: prsm.database.health
  rules:
  - alert: PostgreSQLDown
    expr: up{job="postgres"} == 0
    for: 1m
    labels:
      severity: critical
      service: database
      category: availability
    annotations:
      summary: "PostgreSQL database is down"
      description: "PostgreSQL database has been down for more than 1 minute."
      runbook_url: "https://docs.prsm.org/runbooks/postgresql-down"

  - alert: PostgreSQLHighConnections
    expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
    for: 5m
    labels:
      severity: warning
      service: database
      category: capacity
    annotations:
      summary: "PostgreSQL connection usage is high"
      description: "PostgreSQL is using {{ $value | humanizePercentage }} of available connections."
      runbook_url: "https://docs.prsm.org/runbooks/high-db-connections"

  - alert: PostgreSQLSlowQueries
    expr: pg_stat_activity_max_tx_duration > 300
    for: 2m
    labels:
      severity: warning
      service: database
      category: performance
    annotations:
      summary: "PostgreSQL has slow running queries"
      description: "PostgreSQL has queries running for more than {{ $value }}s."
      runbook_url: "https://docs.prsm.org/runbooks/slow-queries"

  - alert: PostgreSQLDeadlocks
    expr: rate(pg_stat_database_deadlocks[5m]) > 0
    for: 1m
    labels:
      severity: warning
      service: database
      category: performance
    annotations:
      summary: "PostgreSQL deadlocks detected"
      description: "PostgreSQL is experiencing {{ $value }} deadlocks/second."
      runbook_url: "https://docs.prsm.org/runbooks/deadlocks"

# =============================================================================
# Redis Cache Alerts
# =============================================================================
- name: prsm.redis.health
  rules:
  - alert: RedisDown
    expr: up{job="redis"} == 0
    for: 1m
    labels:
      severity: critical
      service: redis
      category: availability
    annotations:
      summary: "Redis cache is down"
      description: "Redis cache has been down for more than 1 minute."
      runbook_url: "https://docs.prsm.org/runbooks/redis-down"

  - alert: RedisHighMemoryUsage
    expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
    for: 5m
    labels:
      severity: warning
      service: redis
      category: capacity
    annotations:
      summary: "Redis memory usage is high"
      description: "Redis is using {{ $value | humanizePercentage }} of available memory."
      runbook_url: "https://docs.prsm.org/runbooks/redis-memory"

  - alert: RedisHighConnectionCount
    expr: redis_connected_clients > 100
    for: 5m
    labels:
      severity: warning
      service: redis
      category: capacity
    annotations:
      summary: "Redis has high connection count"
      description: "Redis has {{ $value }} client connections, which is above normal."
      runbook_url: "https://docs.prsm.org/runbooks/redis-connections"

# =============================================================================
# IPFS Storage Alerts
# =============================================================================
- name: prsm.ipfs.health
  rules:
  - alert: IPFSDown
    expr: up{job="ipfs"} == 0
    for: 2m
    labels:
      severity: critical
      service: ipfs
      category: availability
    annotations:
      summary: "IPFS node is down"
      description: "IPFS node has been down for more than 2 minutes."
      runbook_url: "https://docs.prsm.org/runbooks/ipfs-down"

  - alert: IPFSHighStorageUsage
    expr: ipfs_repo_size_bytes / ipfs_repo_size_limit_bytes > 0.85
    for: 10m
    labels:
      severity: warning
      service: ipfs
      category: capacity
    annotations:
      summary: "IPFS storage usage is high"
      description: "IPFS repository is using {{ $value | humanizePercentage }} of available storage."
      runbook_url: "https://docs.prsm.org/runbooks/ipfs-storage"

  - alert: IPFSLowPeerCount
    expr: ipfs_swarm_peers < 5
    for: 10m
    labels:
      severity: warning
      service: ipfs
      category: connectivity
    annotations:
      summary: "IPFS has low peer count"
      description: "IPFS node has only {{ $value }} peers, which may affect content availability."
      runbook_url: "https://docs.prsm.org/runbooks/ipfs-peers"

# =============================================================================
# FTNS Token & Web3 Alerts
# =============================================================================
- name: prsm.web3.health
  rules:
  - alert: Web3ConnectionFailure
    expr: increase(web3_connection_failures_total[5m]) > 5
    for: 2m
    labels:
      severity: warning
      service: web3
      category: connectivity
    annotations:
      summary: "Web3 connection failures detected"
      description: "{{ $value }} Web3 connection failures in the last 5 minutes."
      runbook_url: "https://docs.prsm.org/runbooks/web3-connection"

  - alert: FTNSTokenTransferFailure
    expr: increase(ftns_transfer_failures_total[10m]) > 3
    for: 1m
    labels:
      severity: critical
      service: web3
      category: functionality
    annotations:
      summary: "FTNS token transfer failures"
      description: "{{ $value }} FTNS token transfer failures in the last 10 minutes."
      runbook_url: "https://docs.prsm.org/runbooks/ftns-transfers"

  - alert: HighGasPrice
    expr: polygon_gas_price_gwei > 50
    for: 15m
    labels:
      severity: warning
      service: web3
      category: cost
    annotations:
      summary: "High gas prices on Polygon network"
      description: "Gas price is {{ $value }} Gwei, which is above normal levels."
      runbook_url: "https://docs.prsm.org/runbooks/high-gas"

# =============================================================================
# Security & Safety Alerts
# =============================================================================
- name: prsm.security.alerts
  rules:
  - alert: CircuitBreakerTriggered
    expr: prsm_circuit_breaker_state > 0
    for: 0s
    labels:
      severity: critical
      service: safety
      category: security
    annotations:
      summary: "PRSM safety circuit breaker triggered"
      description: "Circuit breaker activated with threat level {{ $value }}. System safety measures engaged."
      runbook_url: "https://docs.prsm.org/runbooks/circuit-breaker"

  - alert: SecurityThreatDetected
    expr: increase(security_threats_detected_total[5m]) > 0
    for: 0s
    labels:
      severity: critical
      service: security
      category: security
    annotations:
      summary: "Security threat detected"
      description: "{{ $value }} security threats detected in the last 5 minutes."
      runbook_url: "https://docs.prsm.org/runbooks/security-threat"

  - alert: UnauthorizedAccessAttempt
    expr: increase(http_requests_total{status="401"}[5m]) > 20
    for: 2m
    labels:
      severity: warning
      service: security
      category: security
    annotations:
      summary: "High number of unauthorized access attempts"
      description: "{{ $value }} unauthorized access attempts in the last 5 minutes."
      runbook_url: "https://docs.prsm.org/runbooks/unauthorized-access"

  - alert: AbnormalUserBehavior
    expr: increase(user_anomaly_score[10m]) > 0.8
    for: 5m
    labels:
      severity: warning
      service: security
      category: security
    annotations:
      summary: "Abnormal user behavior detected"
      description: "User anomaly score is {{ $value }}, indicating potential security concern."
      runbook_url: "https://docs.prsm.org/runbooks/user-anomaly"

# =============================================================================
# Infrastructure Alerts
# =============================================================================
- name: prsm.infrastructure.health
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 10m
    labels:
      severity: warning
      category: performance
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is {{ $value }}% on {{ $labels.instance }}."
      runbook_url: "https://docs.prsm.org/runbooks/high-cpu"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
    for: 10m
    labels:
      severity: warning
      category: performance
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}."
      runbook_url: "https://docs.prsm.org/runbooks/high-memory"

  - alert: LowDiskSpace
    expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
    for: 10m
    labels:
      severity: warning
      category: capacity
    annotations:
      summary: "Low disk space detected"
      description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}:{{ $labels.mountpoint }}."
      runbook_url: "https://docs.prsm.org/runbooks/low-disk"

  - alert: NetworkLatencyHigh
    expr: histogram_quantile(0.95, rate(network_latency_seconds_bucket[5m])) > 0.1
    for: 5m
    labels:
      severity: warning
      category: performance
    annotations:
      summary: "High network latency detected"
      description: "95th percentile network latency is {{ $value }}s."
      runbook_url: "https://docs.prsm.org/runbooks/network-latency"

# =============================================================================
# Business Logic Alerts
# =============================================================================
- name: prsm.business.metrics
  rules:
  - alert: LowModelTrainingSuccessRate
    expr: rate(model_training_success_total[1h]) / rate(model_training_attempts_total[1h]) < 0.8
    for: 30m
    labels:
      severity: warning
      service: training
      category: business
    annotations:
      summary: "Low model training success rate"
      description: "Model training success rate is {{ $value | humanizePercentage }} over the last hour."
      runbook_url: "https://docs.prsm.org/runbooks/training-success"

  - alert: MarketplaceTransactionFailures
    expr: increase(marketplace_transaction_failures_total[30m]) > 5
    for: 5m
    labels:
      severity: warning
      service: marketplace
      category: business
    annotations:
      summary: "High marketplace transaction failure rate"
      description: "{{ $value }} marketplace transaction failures in the last 30 minutes."
      runbook_url: "https://docs.prsm.org/runbooks/marketplace-failures"

  - alert: GovernanceParticipationLow
    expr: governance_active_voters / governance_total_eligible < 0.1
    for: 1h
    labels:
      severity: warning
      service: governance
      category: business
    annotations:
      summary: "Low governance participation"
      description: "Only {{ $value | humanizePercentage }} of eligible voters are participating in governance."
      runbook_url: "https://docs.prsm.org/runbooks/governance-participation"