"""
Phase 3.x.3 Task 3 — Python client for ``PublisherKeyAnchor.sol``.

Wraps the on-chain contract with a single class:

- ``register_self(identity)`` — register THIS node's pubkey on-chain.
  Requires a configured wallet (private key) at construction. Idempotent
  at the contract level: if already registered, the contract reverts and
  this client surfaces it as ``PublisherAlreadyRegisteredError``.
- ``lookup(node_id) → Optional[str]`` — base64-encoded pubkey, or None
  if not registered. TTL-cached (default 1 hour) so repeated verification
  of artifacts from the same publisher doesn't hit the chain.
- ``invalidate(node_id)`` — explicit cache eviction. Useful for operators
  who know an ``adminOverride`` just happened and want their next lookup
  to re-fetch.

Same Web3.py 7.x idiom as the existing PRSM economy clients
(``prsm.economy.web3.stake_manager``, etc.). Optional import gate so
``HAS_WEB3 = False`` lets unit tests run on systems without web3
installed (the read-only path doesn't need eth_account either).

Trust model upgrade per Phase 3.x.3 design plan §1.4: callers that go
through this client get cross-node trust (anchor) instead of local-
sidecar trust (Phase 3.x.2 / 3.x.4 default). Combine with
``verify_X_with_anchor`` wrappers (Task 4) for the verifier path.
"""

from __future__ import annotations

import base64
import logging
import time
from typing import Any, Optional, Tuple

from prsm.node.identity import NodeIdentity
from prsm.security.publisher_key_anchor.exceptions import (
    AnchorRPCError,
    PublisherAlreadyRegisteredError,
    PublisherKeyAnchorError,
)

try:
    from eth_account import Account
    from web3 import Web3
    from web3.contract import Contract

    HAS_WEB3 = True
except ImportError:  # pragma: no cover
    HAS_WEB3 = False
    Web3 = None  # type: ignore
    Account = None  # type: ignore
    Contract = None  # type: ignore


logger = logging.getLogger(__name__)


# Minimal ABI for PublisherKeyAnchor.sol — register, adminOverride
# (operators only), and lookup. Full ABI is generated by Hardhat at
# compile time but we only need these three entry points client-side.
PUBLISHER_KEY_ANCHOR_ABI = [
    {
        "type": "function",
        "name": "register",
        "stateMutability": "nonpayable",
        "inputs": [{"name": "publicKey", "type": "bytes"}],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "lookup",
        "stateMutability": "view",
        "inputs": [{"name": "nodeId", "type": "bytes16"}],
        "outputs": [{"name": "", "type": "bytes"}],
    },
    {
        "type": "function",
        "name": "admin",
        "stateMutability": "view",
        "inputs": [],
        "outputs": [{"name": "", "type": "address"}],
    },
    # Custom errors — matching the contract definitions so revert
    # decoding produces meaningful messages.
    {
        "type": "error",
        "name": "AlreadyRegistered",
        "inputs": [{"name": "nodeId", "type": "bytes16"}],
    },
    {
        "type": "error",
        "name": "InvalidPublicKeyLength",
        "inputs": [{"name": "actual", "type": "uint256"}],
    },
    {
        "type": "error",
        "name": "NotAdmin",
        "inputs": [{"name": "caller", "type": "address"}],
    },
    {
        "type": "error",
        "name": "NotRegistered",
        "inputs": [{"name": "nodeId", "type": "bytes16"}],
    },
]


# Cache sentinel: distinguishes "we asked the chain and nothing is
# registered" (should still hit cache) from "we never asked" (None).
_NEGATIVE_CACHE = object()


def _node_id_to_bytes16(node_id: str) -> bytes:
    """Convert PRSM's hex node_id (32 chars from sha256(pubkey)[:16])
    into the 16-byte ``bytes16`` the contract expects.

    Validates length defensively so a malformed node_id surfaces as a
    clear error rather than a confusing on-chain revert.
    """
    if not isinstance(node_id, str):
        raise ValueError(
            f"node_id must be a hex string, got {type(node_id).__name__}"
        )
    # Strip optional 0x prefix; PRSM's NodeIdentity stores bare hex.
    s = node_id[2:] if node_id.startswith("0x") else node_id
    if len(s) != 32:
        raise ValueError(
            f"node_id must be 32 hex chars (16 bytes), got {len(s)} chars"
        )
    try:
        return bytes.fromhex(s)
    except ValueError as exc:
        raise ValueError(f"node_id is not valid hex: {exc}") from exc


class PublisherKeyAnchorClient:
    """Wraps the on-chain ``PublisherKeyAnchor`` contract.

    Construction modes:
      - **Read-only** (``private_key=None``): supports ``lookup`` only.
        ``register_self`` raises. Suitable for verifiers that don't
        publish.
      - **Read-write** (``private_key`` supplied): supports both
        ``register_self`` and ``lookup``.

    The hot path is ``lookup``; verifiers call it on every cross-node
    artifact verification. TTL-cached (default 1 hour) so repeated
    verification of artifacts from the same publisher doesn't hit the
    chain.

    Concurrency: this class is not thread-safe by design. Callers
    needing multi-thread access should serialize on their own.
    """

    def __init__(
        self,
        contract_address: str,
        rpc_url: Optional[str] = None,
        *,
        private_key: Optional[str] = None,
        cache_ttl_seconds: int = 3600,
        web3: Optional[Any] = None,
        contract: Optional[Any] = None,
    ) -> None:
        """Construct the client.

        Args:
            contract_address: Deployed PublisherKeyAnchor address (hex).
            rpc_url: HTTP RPC endpoint. Required unless ``web3`` is
                supplied directly (test injection).
            private_key: Wallet private key for ``register_self``.
                Optional; absent means read-only.
            cache_ttl_seconds: Lookup-cache TTL.
            web3: Optional pre-built Web3 instance (test injection).
            contract: Optional pre-built contract instance (test
                injection — bypasses the ABI binding).

        Test injection (``web3``/``contract``) lets unit tests exercise
        the client without spinning up a real RPC or chain.
        """
        if not HAS_WEB3 and (web3 is None and contract is None):
            raise RuntimeError(
                "web3 + eth_account packages required for live RPC; "
                "install with `pip install web3 eth-account` OR pass "
                "an injected web3/contract for tests"
            )

        if contract is not None:
            self._contract = contract
            self._web3 = web3  # may be None for read-only mocks
            self._contract_address = contract_address
        else:
            if web3 is not None:
                self._web3 = web3
            else:
                if rpc_url is None:
                    raise ValueError(
                        "either rpc_url or web3 must be provided"
                    )
                self._web3 = Web3(Web3.HTTPProvider(rpc_url))
            self._contract_address = Web3.to_checksum_address(contract_address)
            self._contract = self._web3.eth.contract(
                address=self._contract_address,
                abi=PUBLISHER_KEY_ANCHOR_ABI,
            )

        self._account = None
        if private_key:
            if not HAS_WEB3:
                raise RuntimeError(
                    "eth_account package required to sign transactions"
                )
            self._account = Account.from_key(private_key)

        self._cache_ttl = int(cache_ttl_seconds)
        # node_id (lowercase hex) → (cached_value, expires_at_monotonic)
        # cached_value is either base64 string OR _NEGATIVE_CACHE for
        # known-unregistered (avoid re-querying every time).
        self._cache: dict[str, Tuple[Any, float]] = {}

    # ── Read path ─────────────────────────────────────────────────────

    @property
    def address(self) -> str:
        """Contract address (checksummed)."""
        return self._contract_address

    @property
    def signer_address(self) -> Optional[str]:
        """Address of the configured signing wallet, if any."""
        return self._account.address if self._account is not None else None

    def lookup(self, node_id: str) -> Optional[str]:
        """Resolve ``node_id`` to its base64-encoded public key.

        Returns ``None`` if the publisher isn't registered. TTL-cached;
        fresh contract read on miss or expiry.

        Raises:
            ValueError: malformed ``node_id`` (not a 32-hex-char string).
            AnchorRPCError: RPC call failed at the transport level.
        """
        # Type-check FIRST. Bytes objects have a .lower() method too,
        # so the .lower() + .startswith() chain below would silently
        # accept bytes input and only fail later with a confusing
        # TypeError on startswith("0x").
        if not isinstance(node_id, str):
            raise ValueError(
                f"node_id must be a hex string, got {type(node_id).__name__}"
            )
        node_id_lower = node_id.lower()
        if node_id_lower.startswith("0x"):
            node_id_lower = node_id_lower[2:]

        cached = self._cache.get(node_id_lower)
        if cached is not None:
            value, expires_at = cached
            if time.monotonic() < expires_at:
                if value is _NEGATIVE_CACHE:
                    return None
                return value

        # Cache miss / expired — fetch fresh.
        try:
            raw_bytes = self._call_lookup(_node_id_to_bytes16(node_id_lower))
        except ValueError:
            raise
        except Exception as exc:
            raise AnchorRPCError(
                f"lookup({node_id_lower}) RPC failed: {exc}"
            ) from exc

        expires_at = time.monotonic() + self._cache_ttl
        if not raw_bytes:
            self._cache[node_id_lower] = (_NEGATIVE_CACHE, expires_at)
            return None

        if len(raw_bytes) != 32:
            # Defensive: contract guarantees 32-byte keys, but a
            # downgraded / forked contract could deviate. Don't trust it.
            raise AnchorRPCError(
                f"contract returned pubkey of unexpected length "
                f"{len(raw_bytes)} (expected 32)"
            )

        b64 = base64.b64encode(raw_bytes).decode("ascii")
        self._cache[node_id_lower] = (b64, expires_at)
        return b64

    def invalidate(self, node_id: str) -> None:
        """Explicit cache eviction for one node_id.

        Operators who know an ``adminOverride`` just happened can call
        this to force the next lookup to re-fetch from the chain.
        """
        node_id_lower = node_id.lower()
        if node_id_lower.startswith("0x"):
            node_id_lower = node_id_lower[2:]
        self._cache.pop(node_id_lower, None)

    def invalidate_all(self) -> None:
        """Clear the entire lookup cache."""
        self._cache.clear()

    # ── Write path ────────────────────────────────────────────────────

    def register_self(self, identity: NodeIdentity) -> str:
        """Register THIS node's pubkey on-chain. Returns tx hash (hex).

        Requires a configured signing wallet (``private_key`` at
        construction). Idempotent at the contract level: re-registering
        an already-registered node_id reverts and surfaces as
        ``PublisherAlreadyRegisteredError`` — callers MAY treat that as
        a benign no-op.

        Raises:
            RuntimeError: read-only client (no signing wallet).
            PublisherAlreadyRegisteredError: contract reverted because
                the node_id is already registered.
            AnchorRPCError: any other RPC / broadcast failure.
        """
        if self._account is None:
            raise RuntimeError(
                "register_self requires a signing wallet — pass "
                "private_key at construction"
            )

        pubkey_bytes = identity.public_key_bytes
        if len(pubkey_bytes) != 32:
            raise ValueError(
                f"identity.public_key_bytes must be 32 bytes, "
                f"got {len(pubkey_bytes)}"
            )

        try:
            tx_hash = self._call_register(pubkey_bytes)
        except PublisherKeyAnchorError:
            raise
        except Exception as exc:
            # Decode the revert if we can — web3 7.x exposes a custom
            # error name on ContractCustomError.
            err_name = getattr(exc, "error_name", None) or str(exc)
            if "AlreadyRegistered" in err_name:
                raise PublisherAlreadyRegisteredError(
                    f"node_id={identity.node_id} already registered on-chain"
                ) from exc
            raise AnchorRPCError(
                f"register_self for node_id={identity.node_id} failed: {exc}"
            ) from exc

        # Successful registration — populate cache so the next lookup
        # of this node returns immediately.
        node_id_lower = identity.node_id.lower()
        b64 = base64.b64encode(pubkey_bytes).decode("ascii")
        expires_at = time.monotonic() + self._cache_ttl
        self._cache[node_id_lower] = (b64, expires_at)
        return tx_hash

    # ── Internal contract wrappers (overridable for tests) ────────────

    def _call_lookup(self, node_id_bytes16: bytes) -> bytes:
        """Call ``contract.lookup(bytes16)``. Returns raw bytes; empty
        bytes mean unregistered.

        Isolated as a single-line method so unit tests can patch it
        without mocking the full Web3 contract chain.
        """
        return self._contract.functions.lookup(node_id_bytes16).call()

    def _call_register(self, pubkey_bytes: bytes) -> str:
        """Call ``contract.register(bytes)``. Returns tx hash (hex).

        Builds + signs + broadcasts the transaction synchronously,
        waits for the receipt. Same idiom as
        ``StakeBondClient.bond`` in the existing economy clients.
        """
        if self._web3 is None or self._account is None:
            raise RuntimeError("web3 and signing account both required for register")

        nonce = self._web3.eth.get_transaction_count(self._account.address)
        tx = self._contract.functions.register(pubkey_bytes).build_transaction(
            {
                "from": self._account.address,
                "nonce": nonce,
                # gas + gasPrice/maxFeePerGas left to the provider's
                # defaults (web3.py 7.x estimates from the network).
            }
        )
        signed = self._account.sign_transaction(tx)
        # web3.py 7.x renamed rawTransaction → raw_transaction; support both.
        raw = getattr(signed, "raw_transaction", None) or signed.rawTransaction
        tx_hash = self._web3.eth.send_raw_transaction(raw)
        receipt = self._web3.eth.wait_for_transaction_receipt(tx_hash)
        if receipt.status != 1:
            raise AnchorRPCError(
                f"register tx {tx_hash.hex()} mined but reverted; "
                f"check explorer for reason"
            )
        return tx_hash.hex()
