class Prsm < Formula
  include Language::Python::Virtualenv

  desc "Protocol for Research, Storage, and Modeling — decentralized AI compute network"
  homepage "https://github.com/prsm-network/PRSM"
  # SHA256 placeholder — regenerated by ops/homebrew-tap/scripts/regenerate-formula.sh
  # after each prsm-network PyPI publish. Until the placeholder is replaced
  # with a real value, `brew install prsm` will fail at the integrity check
  # (this is intentional during the pre-mainnet scaffold phase).
  url "https://files.pythonhosted.org/packages/source/p/prsm-network/prsm-network-1.7.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"
  head "https://github.com/prsm-network/PRSM.git", branch: "main"

  depends_on "python@3.12"

  # Transitive Python dependencies are declared as `resource` blocks below.
  # The `homebrew-pypi-poet` tool generates this list from a built virtualenv
  # — see scripts/regenerate-formula.sh for the regeneration command.
  #
  # The current list is a SUBSET — only the most stable / widely-used direct
  # dependencies. The full set is regenerated post-PyPI-publish so sha256
  # values match the actually-published wheels rather than placeholder hashes.

  resource "aiohttp" do
    url "https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.10.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/source/c/click/click-8.1.7.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "cryptography" do
    url "https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-44.0.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "mcp" do
    url "https://files.pythonhosted.org/packages/source/m/mcp/mcp-0.9.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "structlog" do
    url "https://files.pythonhosted.org/packages/source/s/structlog/structlog-24.4.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "wasmtime" do
    url "https://files.pythonhosted.org/packages/source/w/wasmtime/wasmtime-25.0.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "web3" do
    url "https://files.pythonhosted.org/packages/source/w/web3/web3-7.5.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  # Additional transitive dependencies — populated by regenerate-formula.sh
  # (libtorrent-python, eth-account, eth-utils, pydantic, fastapi, uvicorn,
  # numpy, msgpack, etc.). Omitted from this scaffold for readability;
  # regeneration produces the full list automatically.

  def install
    virtualenv_install_with_resources
  end

  test do
    # Smoke test: PRSM CLI runs and reports a version
    assert_match(/PRSM|prsm/i, shell_output("#{bin}/prsm --version 2>&1", 0))

    # MCP server stdio purity check — server starts, accepts stdin EOF cleanly
    require "open3"
    Open3.popen3("#{bin}/prsm", "mcp-server") do |stdin, _stdout, _stderr, wait|
      stdin.close
      Process.kill("TERM", wait.pid) rescue nil
      wait.value
    end
  end
end
