/**
 * Alert-Router Smoke Test
 *
 * Posts a synthetic finding to all configured channels at each
 * severity level, so an operator can verify end-to-end that
 * Discord / Slack / PagerDuty / email are all wired correctly
 * before mainnet bot deploy.
 *
 * Usage:
 *
 *   # Configure all 4 channels via env, then:
 *   npm run smoke-test
 *
 *   # Or for a single severity:
 *   npm run smoke-test -- --severity P0
 *
 *   # Or dry-run (no actual POSTs):
 *   PRSM_ALERT_DRY_RUN=1 npm run smoke-test
 *
 * Exit codes:
 *   0 — all configured channels acknowledged the synthetic finding
 *   1 — at least one configured channel rejected the request
 *   2 — config error (no channels configured at all)
 *
 * This is the L10a deploy-time validation per AUDIT_PLAN.md L10a +
 * Exploit Response Playbook §11 readiness checklist.
 */

import { Finding, FindingSeverity, FindingType } from "forta-agent";
import { AlertRouter, PagerSeverity } from "./routing/alert_router";

interface SmokeTestArgs {
  severity?: PagerSeverity | "ALL";
}

function parseArgs(argv: string[]): SmokeTestArgs {
  const args: SmokeTestArgs = { severity: "ALL" };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === "--severity" && i + 1 < argv.length) {
      const sev = argv[++i].toUpperCase() as PagerSeverity;
      if (["P0", "P1", "P2", "P3", "INFO"].includes(sev)) {
        args.severity = sev;
      } else {
        throw new Error(`Invalid --severity ${sev}; expected one of P0|P1|P2|P3|INFO`);
      }
    }
  }
  return args;
}

function pagerToFortaSeverity(p: PagerSeverity): FindingSeverity {
  switch (p) {
    case "P0": return FindingSeverity.Critical;
    case "P1": return FindingSeverity.High;
    case "P2": return FindingSeverity.Medium;
    case "P3": return FindingSeverity.Low;
    case "INFO":
    default:   return FindingSeverity.Info;
  }
}

function buildSyntheticFinding(severity: PagerSeverity): Finding {
  return Finding.fromObject({
    name: `[SMOKE TEST] PRSM Forta Router Validation — ${severity}`,
    description:
      "This is a synthetic finding generated by the smoke-test CLI. " +
      "It validates that the alert-router can fan out to all configured " +
      "channels (Discord war-room, Foundation council Slack, PagerDuty, " +
      "email backup) at the expected severities. If you see this in your " +
      "channel, the wiring works. No action required — this is a test.",
    alertId: `PRSM-SMOKE-${severity}`,
    protocol: "PRSM",
    type: FindingType.Info,
    severity: pagerToFortaSeverity(severity),
    metadata: {
      synthetic: "true",
      timestamp: new Date().toISOString(),
      runner: process.env.USER || "ci",
      purpose: "L10a alert-routing readiness validation",
    },
  });
}

async function runOne(severity: PagerSeverity): Promise<PagerSeverity> {
  const router = new AlertRouter();
  const finding = buildSyntheticFinding(severity);
  console.log(`→ Routing synthetic ${severity} finding...`);
  const routed = await router.route(finding);
  console.log(`← Router classified as ${routed}`);
  if (routed !== severity) {
    throw new Error(
      `Severity round-trip mismatch: sent ${severity}, router returned ${routed}`,
    );
  }
  return routed;
}

function reportConfig(): { configured: string[]; missing: string[] } {
  const channels: Record<string, string | undefined> = {
    "Discord war-room (PRSM_DISCORD_WEBHOOK_URL)": process.env.PRSM_DISCORD_WEBHOOK_URL,
    "Foundation council Slack (PRSM_SLACK_WEBHOOK_URL)": process.env.PRSM_SLACK_WEBHOOK_URL,
    "PagerDuty (PRSM_PAGERDUTY_KEY)": process.env.PRSM_PAGERDUTY_KEY,
    "Email backup (PRSM_ALERT_EMAILS)": process.env.PRSM_ALERT_EMAILS,
  };
  const configured = Object.entries(channels)
    .filter(([, v]) => v && v.length > 0)
    .map(([k]) => k);
  const missing = Object.entries(channels)
    .filter(([, v]) => !v || v.length === 0)
    .map(([k]) => k);
  return { configured, missing };
}

async function main(): Promise<number> {
  const args = parseArgs(process.argv);
  const { configured, missing } = reportConfig();

  console.log("═══ PRSM Alert Router Smoke Test ═══");
  console.log("");
  console.log("Configured channels:");
  if (configured.length === 0) {
    console.error("  (none)");
    console.error("");
    console.error("ERROR: No alert channels configured. Set at least one of:");
    console.error("  PRSM_DISCORD_WEBHOOK_URL");
    console.error("  PRSM_SLACK_WEBHOOK_URL");
    console.error("  PRSM_PAGERDUTY_KEY");
    console.error("  PRSM_ALERT_EMAILS");
    console.error("");
    console.error("Or set PRSM_ALERT_DRY_RUN=1 to validate without channels.");
    if (process.env.PRSM_ALERT_DRY_RUN !== "1") return 2;
  } else {
    configured.forEach((c) => console.log(`  ✓ ${c}`));
  }

  if (missing.length > 0 && process.env.PRSM_ALERT_DRY_RUN !== "1") {
    console.log("");
    console.log("Unconfigured channels (will be skipped):");
    missing.forEach((c) => console.log(`  · ${c}`));
  }

  if (process.env.PRSM_ALERT_DRY_RUN === "1") {
    console.log("");
    console.log("DRY-RUN MODE — no HTTP requests will be made.");
  }

  console.log("");

  const severitiesToTest: PagerSeverity[] =
    args.severity === "ALL"
      ? ["P0", "P1", "P2", "P3"]
      : [args.severity!];

  let failures = 0;
  for (const sev of severitiesToTest) {
    try {
      await runOne(sev);
      console.log(`  ✅ ${sev} OK`);
    } catch (e) {
      console.error(`  ❌ ${sev} FAILED:`, e);
      failures++;
    }
    console.log("");
  }

  if (failures > 0) {
    console.error(`Smoke test FAILED — ${failures} severity level(s) had errors`);
    return 1;
  }

  console.log("Smoke test PASSED — all configured channels acknowledged synthetic findings.");
  console.log("");
  console.log("Next steps:");
  console.log("  1. Verify each channel received the [SMOKE TEST] message.");
  console.log("  2. Have on-call PagerDuty recipient acknowledge the page.");
  console.log("  3. Document the run in the deploy log.");
  console.log("  4. Proceed with bot deploy per Forta Playbook §11.");
  return 0;
}

main()
  .then((code) => process.exit(code))
  .catch((e) => {
    console.error("Smoke test crashed:", e);
    process.exit(1);
  });
