# Promtail configuration for PRSM log collection

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # PRSM application logs
  - job_name: prsm-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: prsm-api
          service: prsm-api
          environment: production
          __path__: /app/logs/*.log

  # Docker container logs
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["app.kubernetes.io/name=prsm"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_app_kubernetes_io_name']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_app_kubernetes_io_component']
        target_label: 'component'

  # System logs
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          service: system
          __path__: /var/log/*.log

  # FTNS transaction logs
  - job_name: ftns-transactions
    static_configs:
      - targets:
          - localhost
        labels:
          job: ftns-transactions
          service: tokenomics
          log_type: transaction
          __path__: /app/logs/ftns/*.log
    pipeline_stages:
      - regex:
          expression: 'FTNS_TRANSACTION: user=(?P<user_id>\w+) amount=(?P<amount>\d+\.?\d*) type=(?P<type>\w+)'
      - labels:
          user_id:
          amount:
          type:

  # Security logs
  - job_name: security-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: security-logs
          service: security
          log_type: security
          __path__: /app/logs/security/*.log
    pipeline_stages:
      - regex:
          expression: 'SECURITY_EVENT: level=(?P<level>\w+) event=(?P<event>\w+) source=(?P<source>[\d\.]+)'
      - labels:
          level:
          event:
          source:

  # Performance logs
  - job_name: performance-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: performance-logs
          service: performance
          log_type: performance
          __path__: /app/logs/performance/*.log
    pipeline_stages:
      - regex:
          expression: 'PERF: operation=(?P<operation>\w+) duration=(?P<duration>\d+\.?\d*)ms user=(?P<user_id>\w+)'
      - labels:
          operation:
          duration:
          user_id: