apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prsm-api-monitor
  namespace: prsm-production
  labels:
    app.kubernetes.io/name: prsm-api
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prsm-api
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prsm-worker-monitor
  namespace: prsm-production
  labels:
    app.kubernetes.io/name: prsm-worker
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prsm-worker
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prsm-alerts
  namespace: prsm-production
  labels:
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: prsm.rules
    rules:
    - alert: PRSMHighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "PRSM is experiencing high error rate: {{ $value }}"
    - alert: PRSMHighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "PRSM 95th percentile response time is {{ $value }}s"
    - alert: PRSMPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"