# Production HPA patches for enhanced autoscaling
- op: replace
  path: /spec/minReplicas
  value: 5
- op: replace
  path: /spec/maxReplicas
  value: 20
- op: replace
  path: /spec/targetCPUUtilizationPercentage
  value: 60
- op: add
  path: /spec/behavior
  value:
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min