apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prsm-production-cert
  namespace: prsm-production
spec:
  secretName: prsm-production-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - prsm.org
  - www.prsm.org
  usages:
  - digital signature
  - key encipherment
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: security@prsm.org
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx