apiVersion: v1
kind: ServiceAccount
metadata:
  name: prsm-api
  namespace: prsm-production
  labels:
    app: prsm-api
    component: api
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prsm-consensus
  namespace: prsm-production
  labels:
    app: prsm-consensus
    component: consensus
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prsm-federation
  namespace: prsm-production
  labels:
    app: prsm-federation
    component: federation
    environment: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prsm-pod-reader
  namespace: prsm-production
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prsm-api-pod-reader
  namespace: prsm-production
subjects:
- kind: ServiceAccount
  name: prsm-api
  namespace: prsm-production
roleRef:
  kind: Role
  name: prsm-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prsm-consensus-pod-reader
  namespace: prsm-production
subjects:
- kind: ServiceAccount
  name: prsm-consensus
  namespace: prsm-production
roleRef:
  kind: Role
  name: prsm-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prsm-federation-pod-reader
  namespace: prsm-production
subjects:
- kind: ServiceAccount
  name: prsm-federation
  namespace: prsm-production
roleRef:
  kind: Role
  name: prsm-pod-reader
  apiGroup: rbac.authorization.k8s.io