apiVersion: v1
kind: Secret
metadata:
  name: prsm-secrets
  namespace: prsm-production
  labels:
    app: prsm
    environment: production
type: Opaque
data:
  # Database credentials (base64 encoded placeholders - will be populated by external-secrets-operator)
  DB_HOST: ""
  DB_PORT: ""
  DB_NAME: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""
  
  # Redis credentials
  REDIS_HOST: ""
  REDIS_PORT: ""
  REDIS_AUTH_TOKEN: ""
  
  # Milvus credentials
  MILVUS_HOST: ""
  MILVUS_PORT: ""
  MILVUS_USER: ""
  MILVUS_PASSWORD: ""
  
  # JWT and encryption keys
  JWT_SECRET_KEY: ""
  ENCRYPTION_KEY: ""
  
  # API keys for external services
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""