"""Sprint 800 — `prsm node init` writes a starter env-file template.

Pairs with sprint-696 `prsm node parallax-readiness`. Readiness
tells you what's MISSING; init writes a TEMPLATE with every
documented env var, descriptions, and placeholder values so the
operator has a single file to fill out + include in systemd
via `EnvironmentFile=`.

  prsm node init [--output PATH]
                 [--force] [--dry-run]

Default output: ~/.prsm/operator.env (chmod 600 — file may
eventually hold PRIVATE_KEY).

File format:
  # ───────────────────────────────────────────────
  # PRSM operator config — generated by `prsm node init`
  # Use:  Environment=...  or  EnvironmentFile=...  in systemd.
  # ───────────────────────────────────────────────

  # <env-var name>
  #   <description>
  #   Allowed values: <values when set>   (if applicable)
  # <env-var>=<placeholder>

Required vars are marked "# REQUIRED" comments above the line so
operators see them at a glance. Placeholder is empty (just the
`=` so the line is uncommented), since most operators want to
fill it themselves rather than have a default leak in.

Pin tests:
- Command registered.
- File written to --output path.
- File contains all registry env-var names.
- Required vars marked "# REQUIRED" in the file.
- Descriptions present.
- Allowed-values lists present when registry had them.
- Existing file → exit 1 (unless --force).
- --force overwrites.
- --dry-run prints to stdout + doesn't write the file.
- chmod 600 applied (posix).
"""
from __future__ import annotations

from pathlib import Path

from click.testing import CliRunner


def _invoke(args=None, env=None):
    from prsm.cli import node as _node_group
    runner = CliRunner()
    return runner.invoke(
        _node_group, ["init"] + (args or []), env=env or {},
    )


# ---- Command registration ---------------------------------------


def test_init_command_registered():
    from prsm.cli import node as _node_group
    cmd_names = [c.name for c in _node_group.commands.values()]
    assert "init" in cmd_names


# ---- File written to --output ----------------------------------


def test_init_writes_to_output_path(tmp_path: Path):
    target = tmp_path / "operator.env"
    result = _invoke(["--output", str(target)])
    assert result.exit_code == 0, result.output
    assert target.exists()
    content = target.read_text()
    # Must include at least one known registry var
    assert "PRSM_INFERENCE_EXECUTOR" in content


def test_init_includes_all_registry_vars(tmp_path: Path):
    """File mentions every name from _PARALLAX_ENV_REGISTRY so
    operators see the full surface they can configure."""
    from prsm.cli import _PARALLAX_ENV_REGISTRY

    target = tmp_path / "operator.env"
    _invoke(["--output", str(target)])
    content = target.read_text()
    for name, _required, _vals, _desc in _PARALLAX_ENV_REGISTRY:
        assert name in content, (
            f"Sprint 800: init template missing {name}"
        )


def test_init_marks_required_vars(tmp_path: Path):
    """Required vars labelled '# REQUIRED' in the file."""
    target = tmp_path / "operator.env"
    _invoke(["--output", str(target)])
    content = target.read_text()
    assert "# REQUIRED" in content


def test_init_includes_descriptions(tmp_path: Path):
    """Description text from the registry appears in the file
    so operators see WHY a var matters without grepping source."""
    from prsm.cli import _PARALLAX_ENV_REGISTRY

    target = tmp_path / "operator.env"
    _invoke(["--output", str(target)])
    content = target.read_text()
    # Sample a few registry descriptions
    first_desc = _PARALLAX_ENV_REGISTRY[0][3]
    # Strip to a stable prefix that wouldn't be mangled by line
    # wrapping. The first 30 chars of the first description
    # should appear verbatim in the file.
    assert first_desc[:30] in content


def test_init_includes_allowed_values_when_present(
    tmp_path: Path,
):
    """Vars with a closed enum (valid_values list) should
    surface those values in the file."""
    target = tmp_path / "operator.env"
    _invoke(["--output", str(target)])
    content = target.read_text()
    # PRSM_INFERENCE_EXECUTOR has ["parallax", "mock", ""]
    assert "parallax" in content


# ---- Refuse to overwrite without --force ----------------------


def test_init_refuses_overwrite_without_force(tmp_path: Path):
    target = tmp_path / "operator.env"
    target.write_text("existing operator config — do not clobber")
    result = _invoke(["--output", str(target)])
    assert result.exit_code != 0
    # File untouched
    assert target.read_text() == (
        "existing operator config — do not clobber"
    )


def test_init_force_overwrites(tmp_path: Path):
    target = tmp_path / "operator.env"
    target.write_text("existing")
    result = _invoke(["--output", str(target), "--force"])
    assert result.exit_code == 0, result.output
    content = target.read_text()
    assert "existing" not in content
    assert "PRSM_INFERENCE_EXECUTOR" in content


# ---- --dry-run prints to stdout, no write ---------------------


def test_init_dry_run_prints_and_does_not_write(
    tmp_path: Path,
):
    target = tmp_path / "operator.env"
    result = _invoke([
        "--output", str(target), "--dry-run",
    ])
    assert result.exit_code == 0, result.output
    assert "PRSM_INFERENCE_EXECUTOR" in result.output
    assert not target.exists()


# ---- chmod 600 -------------------------------------------------


def test_init_chmods_600(tmp_path: Path):
    """Generated file is chmod 600 — may eventually contain
    PRIVATE_KEY or other secrets the operator pastes in."""
    target = tmp_path / "operator.env"
    _invoke(["--output", str(target)])
    mode = target.stat().st_mode & 0o777
    assert mode == 0o600, (
        f"Sprint 800: operator.env must be chmod 600; got {oct(mode)}"
    )


# ---- Default path ---------------------------------------------


def test_init_default_path_under_dot_prsm(
    tmp_path: Path, monkeypatch,
):
    """No --output → ~/.prsm/operator.env. We monkey-patch
    Path.home() to redirect to tmp_path."""
    monkeypatch.setattr("pathlib.Path.home", lambda: tmp_path)
    result = _invoke([])
    assert result.exit_code == 0, result.output
    default_path = tmp_path / ".prsm" / "operator.env"
    assert default_path.exists()
